In [6]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
abc=np.array((32,52,14,25,36))

In [4]:
print(arr)

[1 2 3 4 5 6]


In [7]:
type(arr)

numpy.ndarray

In [8]:
print(arr.ndim)

1


In [9]:
print(arr.size)

6


In [10]:
print(arr.shape)

(6,)


In [11]:
print(arr.dtype)

int64


In [12]:
arr1=np.array([11,22,33,44,55,66],dtype="float")

In [13]:
print(arr1.dtype)

float64


In [7]:
arr2=np.array([[1,2,3],[3,2,1]])

In [8]:
print(arr2)

[[1 2 3]
 [3 2 1]]


In [9]:
arr3=np.array([[[1,2,3],[23,43,53]],[[75,23,132],[23,43,53]]])
print(arr3)
print(arr3.shape)

[[[  1   2   3]
  [ 23  43  53]]

 [[ 75  23 132]
  [ 23  43  53]]]
(2, 2, 3)


In [20]:
arr4=np.zeros((2,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr5=np.random.randint(1,10,(2,3))

In [22]:
print(arr5)

[[9 3 9]
 [5 5 4]]


In [24]:
arr6=np.arange(0,100,5)
print(arr6)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [25]:
arr7=arr5.flatten()
print(arr7)

[9 3 9 5 5 4]


In [26]:
arr8=arr5.reshape(3,2)
print(arr8)

[[9 3]
 [9 5]
 [5 4]]
