In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7])

In [4]:
print(arr)

[1 2 3 4 5 6 7]


In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
arr2.sum()

np.int64(21)

In [7]:
arr2.min()

np.int64(1)

In [8]:
arr2.max()

np.int64(6)

In [9]:
print(np.sum(arr2, axis=0))

[5 7 9]


In [10]:
print(np.min(arr2, axis=1))

[1 4]


In [11]:
print(np.max(arr2, axis=1))

[3 6]


In [12]:
arr2+1

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
arr2-1

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr2*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
arr2**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
arr2/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [17]:
arr3=np.array([[9,8,-7],[9,3,8]])
print(arr3)

[[ 9  8 -7]
 [ 9  3  8]]


In [18]:
print(arr2+arr3)

[[10 10 -4]
 [13  8 14]]


In [19]:
print(arr2-arr3)

[[-8 -6 10]
 [-5  2 -2]]
